version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # api:
  #   build: ./api
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./api:/app
  #     - /app/node_modules
