export type ActivityType =
  | "LOGIN_SUCCESS"
  | "LOGIN_FAILED"
  | "LOGOUT"
  | "USER_CREATED"
  | "USER_BLOCKED"
  | "USER_UNBLOCKED"
  | "USER_DELETED"
  | "PASSWORD_CHANGED"
  | "PROFILE_UPDATED"
  | "USER_RESTRICTED"
  | "USER_UNRESTRICTED"
  | "ADMIN_DELETED_USER"
  | "ADMIN_CREATED_USER"
  | "ADMIN_UPDATED_USER"
  | "ADMIN_CHANGED_PASSWORD"
  | "MODERATOR_VIEWED_QUEUE"
  | "MODERATOR_BLOCKED_USER"
  | "MODERATOR_UNBLOCKED_USER"
  | "POST_APPROVED"
  | "POST_REJECTED"
  | "POST_QUARANTINED";

export interface ActivityLogInput {
  userId: string;
  action: ActivityType;
  details: string;
}
